<?php
/**
 * Created by PhpStorm.
 * User: 大漠孤颜值
 * Date: 2019/9/11
 * Time: 下午3:45
 */

namespace app\home\model;
use think\model;
class UserAnswerModel extends model {

	protected $table = 'yz_user_answer';

	public function insert(array $data = [], $replace = false, $getLastInsID = false, $sequence = null)
	{
		return parent::insert($data, $replace, $getLastInsID, $sequence); // TODO: Change the autogenerated stub
	}
}