<?php
namespace app\common\exception;

use Exception;
use think\exception\Handle;
use think\exception\HttpException;
use think\exception\ValidateException;
class Http extends Handle {
	public function render(Exception $e)
	{
		if ($e instanceof ValidateException) {
			dump(222);
		}
		// 请求异常
		if ($e instanceof HttpException && request()->isAjax()) {
			return response($e->getMessage(), $e->getStatusCode());
		}
//		var_dump(111);die;
		return parent::render($e); // TODO: Change the autogenerated stub
	}
}