<?php
/**
 * Created by PhpStorm.
 * User: 大漠孤颜值
 * Date: 2019/8/27
 * Time: 下午4:08
 */
namespace app\home\model;
use think\model;
class AccountNumberModel extends model
{
	protected $table = 'yz_account_number';

	public function insert(array $data = [], $replace = false, $getLastInsID = false, $sequence = null)
	{
		return parent::insert($data, $replace, $getLastInsID, $sequence); // TODO: Change the autogenerated stub
	}

	public function getAccountNumberList($where = array()) {

		if ($where) {

		}

		$this->select([])->toArray();

		dump($this->getLastSql());
	}
}