<?php
/**
 * Created by PhpStorm.
 * User: 大漠孤颜值
 * Date: 2019/8/27
 * Time: 下午4:08
 */
namespace app\home\model;
use think\model;
class AnswerModel extends model
{
	protected $table = 'yz_answer';

	public function insert(array $data = [], $replace = false, $getLastInsID = false, $sequence = null)
	{
		return parent::insert($data, $replace, $getLastInsID, $sequence); // TODO: Change the autogenerated stub
	}

	public function getAnswerList($where = array()) {

		if (!is_array($where) || empty($where)) {
			return array();
		}
		$list = $this->where($where)->select()->toArray();

		return $list;
//				dump($list);
//				dump($this->getLastSql());
die;
//		return $this->select($where)->toArray();
	}

	public function getQuestionAnswer() {
		$sql = "select * from {$this->table} ";

		$list = $this->query($sql);

		var_dump($list);
		die;
	}
}