<?php
/**
 * Created by PhpStorm.
 * User: 大漠孤颜值
 * Date: 2019/8/27
 * Time: 下午4:08
 */
namespace app\home\model;
use think\model;
class QuestionModel extends model
{
	protected $table = 'yz_question';

	public function insert(array $data = [], $replace = false, $getLastInsID = false, $sequence = null)
	{
		return parent::insert($data, $replace, $getLastInsID, $sequence); // TODO: Change the autogenerated stub
	}

	public function getQuestionList($where = array()) {
		$data = array();
		if ($where) {
			$data = $this->where($where)->select();
		}
		if (empty($data)) {
			return array();
		}
		return $data->toArray();
	}
}